package Presentation;

import BLL.HoaDonBLL;
import BLL.ThongBao_ChuyenDoi;
import static BLL.ThongBao_ChuyenDoi.*;
import static DAL.NhanVienDAL.iQuyenND;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author MinhNguyen
 */
public class frmBangThongKe extends javax.swing.JFrame {
// set dateformat dmy Select * from HoaDon where convert(varchar,NgayTaoHD,103) = '28/08/2016'

    /**
     * Creates new form frmBangThongKe
     */
    public frmBangThongKe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnThongKe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dateFrom = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        dateTo = new com.toedter.calendar.JDateChooser();
        pnlDanhSach = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        chkXemTatCa = new javax.swing.JCheckBox();
        chkTuyChon = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHome = new javax.swing.JMenu();
        mnuiTrangChu = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuiExit = new javax.swing.JMenuItem();
        mnuQuanly = new javax.swing.JMenu();
        mnuSanPham = new javax.swing.JMenu();
        mnuiLoaiSanPham = new javax.swing.JMenuItem();
        mnuiNhaCungCap = new javax.swing.JMenuItem();
        mnuiSanPham = new javax.swing.JMenuItem();
        mnuHoaDon = new javax.swing.JMenu();
        mnuiQLHDNhap = new javax.swing.JMenuItem();
        mnuiQLHDXuat = new javax.swing.JMenuItem();
        mnuiCTHD = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuKhachHang = new javax.swing.JMenuItem();
        mnuNhanVien = new javax.swing.JMenuItem();
        mnuQLTaiKhoan = new javax.swing.JMenuItem();
        mnuHoadon = new javax.swing.JMenu();
        mnuTaoHoaDon = new javax.swing.JMenu();
        mnuiHDNhap = new javax.swing.JMenuItem();
        mnuiHDXuat = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mnuTKHoaDon = new javax.swing.JMenuItem();
        mnuTKNhanVien = new javax.swing.JMenuItem();
        mnuTaiKhoan = new javax.swing.JMenu();
        mnuiDangKy = new javax.swing.JMenuItem();
        mnuiDoiMK = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenu();
        mnuiBanQuyen = new javax.swing.JMenuItem();
        mnuDangXuat = new javax.swing.JMenu();
        mnuTime = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BH - Thống kê hóa đơn");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(170, 234, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 1, true), "Thống kê lương tháng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setToolTipText("");

        btnThongKe.setBackground(new java.awt.Color(255, 255, 255));
        btnThongKe.setText("Tính Lương");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        jLabel1.setText("Từ :");

        dateFrom.setDateFormatString("dd/MM/yyyy");

        jLabel2.setText("đến :");

        dateTo.setDateFormatString("dd/MM/yyyy");

        pnlDanhSach.setBackground(new java.awt.Color(170, 234, 240));
        pnlDanhSach.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 1, true), "Danh sách nhân viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14), new java.awt.Color(51, 102, 255))); // NOI18N

        tblHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Số hóa đơn", "Ngày tạo", "Khách hàng", "Người tạo", "Người bán", "Tổng tiền", "Trạng thái", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        javax.swing.GroupLayout pnlDanhSachLayout = new javax.swing.GroupLayout(pnlDanhSach);
        pnlDanhSach.setLayout(pnlDanhSachLayout);
        pnlDanhSachLayout.setHorizontalGroup(
            pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDanhSachLayout.setVerticalGroup(
            pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );

        chkXemTatCa.setBackground(new java.awt.Color(170, 234, 240));
        buttonGroup1.add(chkXemTatCa);
        chkXemTatCa.setSelected(true);
        chkXemTatCa.setText("Tất cả");

        chkTuyChon.setBackground(new java.awt.Color(170, 234, 240));
        buttonGroup1.add(chkTuyChon);
        chkTuyChon.setText("Tùy chọn ngày");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDanhSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkXemTatCa)
                                .addGap(39, 39, 39)
                                .addComponent(btnThongKe))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkTuyChon)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 324, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(chkTuyChon))
                    .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkXemTatCa)
                    .addComponent(btnThongKe))
                .addGap(18, 18, 18)
                .addComponent(pnlDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDanhSach.getAccessibleContext().setAccessibleName("Danh sách nhân viên");

        mnuHome.setText("Home");

        mnuiTrangChu.setText("Trang chủ");
        mnuiTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiTrangChuActionPerformed(evt);
            }
        });
        mnuHome.add(mnuiTrangChu);
        mnuHome.add(jSeparator4);

        mnuiExit.setText("Thoát");
        mnuiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiExitActionPerformed(evt);
            }
        });
        mnuHome.add(mnuiExit);

        jMenuBar1.add(mnuHome);

        mnuQuanly.setText("Quản lý");

        mnuSanPham.setText("Sản phẩm");

        mnuiLoaiSanPham.setText("Loại sản phẩm");
        mnuiLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiLoaiSanPhamActionPerformed(evt);
            }
        });
        mnuSanPham.add(mnuiLoaiSanPham);

        mnuiNhaCungCap.setText("Nhà cung cấp");
        mnuiNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiNhaCungCapActionPerformed(evt);
            }
        });
        mnuSanPham.add(mnuiNhaCungCap);

        mnuiSanPham.setText("Các sản phẩm");
        mnuiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiSanPhamActionPerformed(evt);
            }
        });
        mnuSanPham.add(mnuiSanPham);

        mnuQuanly.add(mnuSanPham);

        mnuHoaDon.setText("Hóa đơn");

        mnuiQLHDNhap.setText("Hóa đơn nhập");
        mnuHoaDon.add(mnuiQLHDNhap);

        mnuiQLHDXuat.setText("Hóa đơn xuất");
        mnuiQLHDXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiQLHDXuatActionPerformed(evt);
            }
        });
        mnuHoaDon.add(mnuiQLHDXuat);

        mnuiCTHD.setText("Chi tiết hóa đơn");
        mnuiCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiCTHDActionPerformed(evt);
            }
        });
        mnuHoaDon.add(mnuiCTHD);

        mnuQuanly.add(mnuHoaDon);
        mnuQuanly.add(jSeparator2);

        mnuKhachHang.setText("Khách hàng");
        mnuKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKhachHangActionPerformed(evt);
            }
        });
        mnuQuanly.add(mnuKhachHang);

        mnuNhanVien.setText("Nhân viên");
        mnuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNhanVienActionPerformed(evt);
            }
        });
        mnuQuanly.add(mnuNhanVien);

        mnuQLTaiKhoan.setText("Tài khoản người dùng");
        mnuQLTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQLTaiKhoanActionPerformed(evt);
            }
        });
        mnuQuanly.add(mnuQLTaiKhoan);

        jMenuBar1.add(mnuQuanly);

        mnuHoadon.setText("Hóa đơn");

        mnuTaoHoaDon.setText("Tạo hóa đơn");

        mnuiHDNhap.setText("Hóa đơn nhập");
        mnuiHDNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiHDNhapActionPerformed(evt);
            }
        });
        mnuTaoHoaDon.add(mnuiHDNhap);

        mnuiHDXuat.setText("Hóa đơn xuất");
        mnuiHDXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiHDXuatActionPerformed(evt);
            }
        });
        mnuTaoHoaDon.add(mnuiHDXuat);

        mnuHoadon.add(mnuTaoHoaDon);

        jMenuBar1.add(mnuHoadon);

        mnuThongKe.setText("Thống kê");

        mnuTKHoaDon.setText("Hóa đơn");
        mnuTKHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTKHoaDonActionPerformed(evt);
            }
        });
        mnuThongKe.add(mnuTKHoaDon);

        mnuTKNhanVien.setText("Nhân viên");
        mnuThongKe.add(mnuTKNhanVien);

        jMenuBar1.add(mnuThongKe);

        mnuTaiKhoan.setText("Tài khoản");

        mnuiDangKy.setText("Đăng ký");
        mnuiDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiDangKyActionPerformed(evt);
            }
        });
        mnuTaiKhoan.add(mnuiDangKy);

        mnuiDoiMK.setText("Đổi mật khẩu");
        mnuiDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiDoiMKActionPerformed(evt);
            }
        });
        mnuTaiKhoan.add(mnuiDoiMK);

        jMenuBar1.add(mnuTaiKhoan);

        mnuAbout.setText("Thông tin");

        mnuiBanQuyen.setText("Bản quyền");
        mnuiBanQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiBanQuyenActionPerformed(evt);
            }
        });
        mnuAbout.add(mnuiBanQuyen);

        jMenuBar1.add(mnuAbout);

        mnuDangXuat.setText("Đăng xuất");
        mnuDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuDangXuatMousePressed(evt);
            }
        });
        jMenuBar1.add(mnuDangXuat);

        mnuTime.setBackground(new java.awt.Color(255, 0, 0));
        jMenuBar1.add(mnuTime);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Thống kê lương tháng");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        String ngayBatDau = DoiDateChooser(dateFrom).getText();
        String ngayKetThuc = DoiDateChooser(dateTo).getText();
        if (chkXemTatCa.isSelected()) {
            ResultSet rs = HoaDonBLL.LayHoaDonDaHoanThanh();
            HoaDonBLL.DoDuLieuVaoBangThongKe(rs, tblHoaDon);
        } else {
            if(ngayBatDau.equals("") || ngayKetThuc.equals("")){
                ThongBao("Vui lòng chọn ngày !", "Thông báo", 1);
            }else{
            ResultSet rsThongKe = HoaDonBLL.ThongKeTheoNgay(ngayBatDau, ngayKetThuc);
            HoaDonBLL.DoDuLieuVaoBangThongKe(rsThongKe, tblHoaDon);
            }
        }

        String doanhThu = ThongBao_ChuyenDoi.TienVietNam(HoaDonBLL.TinhTongTien(tblHoaDon, 3));
        txtTongDoanhThu.setText(doanhThu);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        DongHo(mnuTime);
        PhanQuyen(mnuNhanVien, mnuQLTaiKhoan, mnuiDangKy, iQuyenND);
        //Thư viện Date
        Date CurrentDate = new Date();

        //Biến lưu định dạng ngày tháng
        String dateCode = new SimpleDateFormat("dd/MM/yyyy").format(CurrentDate);
        //Gán ngày tháng vào text trong form
        DoiDateChooser(dateFrom).setText(dateCode);
                DoiDateChooser(dateTo).setText(dateCode);

        ResultSet rs = HoaDonBLL.LayHoaDonDaHoanThanh();
        HoaDonBLL.DoDuLieuVaoBangThongKe(rs, tblHoaDon);

        String doanhThu = ThongBao_ChuyenDoi.TienVietNam(HoaDonBLL.TinhTongTien(tblHoaDon, 3));
        txtTongDoanhThu.setText(doanhThu);
    }//GEN-LAST:event_formWindowOpened

    private void mnuiTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiTrangChuActionPerformed
        frmTrangChinh tc = new frmTrangChinh();
        tc.show();
        this.dispose();
    }//GEN-LAST:event_mnuiTrangChuActionPerformed

    private void mnuiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiExitActionPerformed
        CauHoiThoat();
    }//GEN-LAST:event_mnuiExitActionPerformed

    private void mnuiLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiLoaiSanPhamActionPerformed
        frmLoaiSanPham lsp = new frmLoaiSanPham();
        lsp.show();
        this.dispose();
    }//GEN-LAST:event_mnuiLoaiSanPhamActionPerformed

    private void mnuiNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiNhaCungCapActionPerformed
        frmNhaCungCap ncc = new frmNhaCungCap();
        ncc.show();
        this.dispose();
    }//GEN-LAST:event_mnuiNhaCungCapActionPerformed

    private void mnuiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiSanPhamActionPerformed
        frmSanPham sp = new frmSanPham();
        sp.show();
        this.dispose();
    }//GEN-LAST:event_mnuiSanPhamActionPerformed

    private void mnuiQLHDXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiQLHDXuatActionPerformed
        frmHoaDon hd = new frmHoaDon();
        hd.show();
        this.dispose();
    }//GEN-LAST:event_mnuiQLHDXuatActionPerformed

    private void mnuiCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiCTHDActionPerformed
        frmChiTietHoaDon cthd = new frmChiTietHoaDon();
        cthd.show();
        this.dispose();
    }//GEN-LAST:event_mnuiCTHDActionPerformed

    private void mnuKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKhachHangActionPerformed
        frmKhachHang kh = new frmKhachHang();
        kh.show();
        this.dispose();
    }//GEN-LAST:event_mnuKhachHangActionPerformed

    private void mnuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNhanVienActionPerformed
        frmNhanVien nv = new frmNhanVien();
        nv.show();
        this.dispose();
    }//GEN-LAST:event_mnuNhanVienActionPerformed

    private void mnuQLTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQLTaiKhoanActionPerformed
        frmDiemDanh qlnd = new frmDiemDanh();
        qlnd.show();
        this.dispose();
    }//GEN-LAST:event_mnuQLTaiKhoanActionPerformed

    private void mnuiHDNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiHDNhapActionPerformed
        frmPhieuNhap pn = new frmPhieuNhap();
        pn.show();
        this.dispose();
    }//GEN-LAST:event_mnuiHDNhapActionPerformed

    private void mnuiHDXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiHDXuatActionPerformed
        frmTaoHoaDon thd = new frmTaoHoaDon();
        thd.show();
        this.dispose();
    }//GEN-LAST:event_mnuiHDXuatActionPerformed

    private void mnuTKHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTKHoaDonActionPerformed
        frmBangThongKe btk = new frmBangThongKe();
        btk.show();
        this.dispose();
    }//GEN-LAST:event_mnuTKHoaDonActionPerformed

    private void mnuiDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiDangKyActionPerformed
        frmDangKy dk = new frmDangKy();
        dk.show();
    }//GEN-LAST:event_mnuiDangKyActionPerformed

    private void mnuiDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiDoiMKActionPerformed
        frmDoiMatKhau dmk = new frmDoiMatKhau();
        dmk.show();
    }//GEN-LAST:event_mnuiDoiMKActionPerformed

    private void mnuiBanQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiBanQuyenActionPerformed
        frmBanQuyen bq = new frmBanQuyen();
        bq.show();
    }//GEN-LAST:event_mnuiBanQuyenActionPerformed

    private void mnuDangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuDangXuatMousePressed
        frmDangNhap dn = new frmDangNhap();
        dn.show();
        this.dispose();
    }//GEN-LAST:event_mnuDangXuatMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBangThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBangThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBangThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBangThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBangThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThongKe;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkTuyChon;
    private javax.swing.JCheckBox chkXemTatCa;
    private com.toedter.calendar.JDateChooser dateFrom;
    private com.toedter.calendar.JDateChooser dateTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu mnuAbout;
    private javax.swing.JMenu mnuDangXuat;
    private javax.swing.JMenu mnuHoaDon;
    private javax.swing.JMenu mnuHoadon;
    private javax.swing.JMenu mnuHome;
    private javax.swing.JMenuItem mnuKhachHang;
    private javax.swing.JMenuItem mnuNhanVien;
    private javax.swing.JMenuItem mnuQLTaiKhoan;
    private javax.swing.JMenu mnuQuanly;
    private javax.swing.JMenu mnuSanPham;
    private javax.swing.JMenuItem mnuTKHoaDon;
    private javax.swing.JMenuItem mnuTKNhanVien;
    private javax.swing.JMenu mnuTaiKhoan;
    private javax.swing.JMenu mnuTaoHoaDon;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuTime;
    private javax.swing.JMenuItem mnuiBanQuyen;
    private javax.swing.JMenuItem mnuiCTHD;
    private javax.swing.JMenuItem mnuiDangKy;
    private javax.swing.JMenuItem mnuiDoiMK;
    private javax.swing.JMenuItem mnuiExit;
    private javax.swing.JMenuItem mnuiHDNhap;
    private javax.swing.JMenuItem mnuiHDXuat;
    private javax.swing.JMenuItem mnuiLoaiSanPham;
    private javax.swing.JMenuItem mnuiNhaCungCap;
    private javax.swing.JMenuItem mnuiQLHDNhap;
    private javax.swing.JMenuItem mnuiQLHDXuat;
    private javax.swing.JMenuItem mnuiSanPham;
    private javax.swing.JMenuItem mnuiTrangChu;
    private javax.swing.JPanel pnlDanhSach;
    private javax.swing.JTable tblHoaDon;
    // End of variables declaration//GEN-END:variables
}
