/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import BLL.NhanVienBLL;
import static BLL.ThongBao_ChuyenDoi.ThongBao;
import DTO.ChucVuDTO;
import java.sql.ResultSet;

/**
 *
 * @author Admin
 */
public class frmChucVu extends javax.swing.JFrame {

    /**
     * Creates new form frmChucVu
     */
    public frmChucVu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChucvu = new javax.swing.JTable();
        lbltenchucvu = new javax.swing.JLabel();
        lblmota = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtmota = new javax.swing.JTextArea();
        txttenchucvu = new javax.swing.JTextField();
        btnThemchucvu = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        lblIdchucvu = new javax.swing.JLabel();
        txtIDchucvu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Vụ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 102, 255))); // NOI18N

        tblChucvu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "IDChucVu", "Tên Chức Vụ", "Mô Tả"
            }
        ));
        tblChucvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChucvuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChucvu);

        lbltenchucvu.setText("Tên Chức Vụ");

        lblmota.setText("Mô Tả");

        txtmota.setColumns(20);
        txtmota.setRows(5);
        jScrollPane2.setViewportView(txtmota);

        btnThemchucvu.setBackground(new java.awt.Color(204, 204, 204));
        btnThemchucvu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemchucvu.setForeground(new java.awt.Color(255, 0, 51));
        btnThemchucvu.setMnemonic('T');
        btnThemchucvu.setText("Thêm Chức vụ");
        btnThemchucvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemchucvuActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(204, 204, 204));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(0, 255, 0));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        lblIdchucvu.setText("ID Chức Vụ");

        txtIDchucvu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtIDchucvu.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbltenchucvu)
                    .addComponent(lblmota)
                    .addComponent(lblIdchucvu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(txttenchucvu)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThemchucvu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtIDchucvu))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdchucvu)
                            .addComponent(txtIDchucvu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltenchucvu)
                            .addComponent(txttenchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmota))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemchucvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemchucvuActionPerformed
        // TODO add your handling code here:
        String tenchucvu = txttenchucvu.getText().trim();
        String mota = txtmota.getText().trim();
//        int idchucvu = Integer.parseInt(txtIDchucvu.getText());
        
        ChucVuDTO cv = new ChucVuDTO(0, tenchucvu, mota);
        NhanVienBLL.ThemChucVu(cv);
        ResultSet rs = NhanVienBLL.LayTatCaDuLieuChucVu();
        NhanVienBLL.DoDuLieuChucVu(rs, tblChucvu);
    }//GEN-LAST:event_btnThemchucvuActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        try{
        String tenchucvu = txttenchucvu.getText().trim();
        String mota = txtmota.getText().trim();
        int idchucvu = Integer.parseInt(txtIDchucvu.getText());
        ChucVuDTO cv = new ChucVuDTO(idchucvu, tenchucvu, mota);
        
       NhanVienBLL.SuaChucVu(cv);
         ResultSet rs = NhanVienBLL.LayTatCaDuLieuChucVu();
        NhanVienBLL.DoDuLieuChucVu(rs, tblChucvu);
        }catch (NumberFormatException e) {
            ThongBao("Vui lòng chọn bản ghi cần sửa !", "Thông báo", 1);
        }
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ResultSet rs = NhanVienBLL.LayTatCaDuLieuChucVu();
        //Thực hiện đổ dữ liệu vào table
        NhanVienBLL.DoDuLieuChucVu(rs, tblChucvu);
//PhanQuyen(mnuNhanVien, mnuQLTaiKhoan, mnuiDangKy, iQuyenND);
//        //Tạo biến ResultSet và thực hiện gán dữ liệu được lấy từ BLL qua hàm LayThongTinNhanVien()
//        ResultSet rsNV = NhanVienBLL.LayThongTinNhanVien();
//        //Gọi hàm đổ dữ liệu vào table THẬT từ BLL
//        NhanVienBLL.DoDuLieuNhanVien(rsNV, tblNhanVien);
//
//        //Tạo biến rs để chứa dữ liệu từ của QuyenNhanVienBLL
//        ResultSet rsQuyen = NhanVienBLL.LayTatCaDuLieuChucVu();
        //Gọi hàm để đổ dữ liệu vào Combobox
       
//
//        //Gọi hàm đổi sang ô text
//        DoiDateChooser(dateNgayVaolam).setText(sdf.format(currentDate));
    }//GEN-LAST:event_formWindowOpened

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        int index = tblChucvu.getSelectedRow();
        txtIDchucvu.setText(tblChucvu.getValueAt(index, 0).toString());
        txttenchucvu.setText(tblChucvu.getValueAt(index, 1).toString());
        txtmota.setText(tblChucvu.getValueAt(index, 2).toString());
        
    }//GEN-LAST:event_formMouseClicked

    private void tblChucvuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChucvuMouseClicked
        // TODO add your handling code here:
        int index = tblChucvu.getSelectedRow();
        txtIDchucvu.setText(tblChucvu.getValueAt(index, 0).toString());
        txttenchucvu.setText(tblChucvu.getValueAt(index, 1).toString());
        txtmota.setText(tblChucvu.getValueAt(index, 2).toString());
    }//GEN-LAST:event_tblChucvuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmChucVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemchucvu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIdchucvu;
    private javax.swing.JLabel lblmota;
    private javax.swing.JLabel lbltenchucvu;
    private javax.swing.JTable tblChucvu;
    private javax.swing.JTextField txtIDchucvu;
    private javax.swing.JTextArea txtmota;
    private javax.swing.JTextField txttenchucvu;
    // End of variables declaration//GEN-END:variables
}
