/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import BLL.NhanVienBLL;
import DTO.CaLamViecDTO;
import java.sql.ResultSet;

/**
 *
 * @author Computer
 */
public class frmCaLamViec extends javax.swing.JFrame {

    /**
     * Creates new form frmCaLamViec
     */
    public frmCaLamViec() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIDCaLamViec = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCaLamViec = new javax.swing.JTable();
        lblMaCa = new javax.swing.JLabel();
        lblMoTa = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        txtMaCa = new javax.swing.JTextField();
        btnThemCaLamViec = new javax.swing.JButton();
        btnXoaCaLamViec = new javax.swing.JButton();
        lblIDcalamviec = new javax.swing.JLabel();
        txtTenCa = new javax.swing.JTextField();
        txtGioKetThuc = new javax.swing.JTextField();
        txtGioBatDau = new javax.swing.JTextField();
        lblTenCa = new javax.swing.JLabel();
        lblGioKetThuc = new javax.swing.JLabel();
        lblGioBatDau = new javax.swing.JLabel();
        btnSuaCaLamViec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CA LÀM VIỆC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));

        txtIDCaLamViec.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtIDCaLamViec.setEnabled(false);

        tblCaLamViec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "IDCa Làm Việc", "Mã Ca ", "Tên Ca", "Giờ Bắt Đầu", "Giờ Kết Thúc", "Ghi Chú"
            }
        ));
        jScrollPane1.setViewportView(tblCaLamViec);

        lblMaCa.setText("Mã Ca");

        lblMoTa.setText("Ghi Chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane2.setViewportView(txtGhiChu);

        btnThemCaLamViec.setBackground(new java.awt.Color(204, 204, 204));
        btnThemCaLamViec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemCaLamViec.setForeground(new java.awt.Color(255, 0, 51));
        btnThemCaLamViec.setMnemonic('T');
        btnThemCaLamViec.setText("Thêm");
        btnThemCaLamViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCaLamViecActionPerformed(evt);
            }
        });

        btnXoaCaLamViec.setBackground(new java.awt.Color(204, 204, 204));
        btnXoaCaLamViec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaCaLamViec.setForeground(new java.awt.Color(0, 0, 204));
        btnXoaCaLamViec.setText("Xóa");
        btnXoaCaLamViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCaLamViecActionPerformed(evt);
            }
        });

        lblIDcalamviec.setText("IDCa Làm Việc");

        txtTenCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenCaActionPerformed(evt);
            }
        });

        txtGioKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGioKetThucActionPerformed(evt);
            }
        });

        txtGioBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGioBatDauActionPerformed(evt);
            }
        });

        lblTenCa.setText("Tên Ca");

        lblGioKetThuc.setText("Giờ Kết Thúc");

        lblGioBatDau.setText("Giờ Bắt Đầu");

        btnSuaCaLamViec.setBackground(new java.awt.Color(204, 204, 204));
        btnSuaCaLamViec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSuaCaLamViec.setForeground(new java.awt.Color(0, 255, 0));
        btnSuaCaLamViec.setText("Sửa");
        btnSuaCaLamViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaCaLamViecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnThemCaLamViec)
                        .addGap(46, 46, 46)
                        .addComponent(btnXoaCaLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnSuaCaLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMaCa)
                                .addComponent(lblTenCa)))
                        .addComponent(lblGioBatDau, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblGioKetThuc, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblMoTa, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(lblIDcalamviec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGioBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGioKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(txtMaCa)
                    .addComponent(txtTenCa)
                    .addComponent(txtIDCaLamViec))
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIDcalamviec)
                            .addComponent(txtIDCaLamViec))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaCa)
                            .addComponent(txtMaCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenCa))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGioBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGioBatDau))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGioKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGioKetThuc))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnThemCaLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnXoaCaLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSuaCaLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblMoTa))))
                        .addGap(116, 116, 116))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemCaLamViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCaLamViecActionPerformed
        // TODO add your handling code here:
        String idcalamviec = txtIDCaLamViec.getText().trim();
        String maca = txtMaCa.getText().trim();
        String tenca = txtTenCa.getText().trim();
        String giobatdau = txtGioBatDau.getText().trim();
        String gioketthuc = txtGioKetThuc.getText().trim();
        String ghichu = txtGhiChu.getText().trim();
//        int idchucvu = Integer.parseInt(txtIDchucvu.getText());
        
        CaLamViecDTO clv = new CaLamViecDTO(0, maca, tenca, giobatdau, gioketthuc, ghichu);
        NhanVienBLL.ThemCaLamViec(clv);
        ResultSet rs = NhanVienBLL.LayTatCaDuLieuCaLamViec();
        NhanVienBLL.DoDuLieuCaLamViec(rs, tblCaLamViec);

        //        int idchucvu = Integer.parseInt(txtIDchucvu.getText());


    }//GEN-LAST:event_btnThemCaLamViecActionPerformed

    private void btnXoaCaLamViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCaLamViecActionPerformed
        // TODO add your handling code here:
        String id = txtIDCaLamViec.getText();
         NhanVienBLL.XoaCaLamViec(id);

        //Tạo biến ResultSet và thực hiện gán dữ liệu được sau khi xóa
        ResultSet rsCLV = NhanVienBLL.LayThongTinNhanVien();
        //Gọi hàm đổ dữ liệu vào table THẬT từ BLL
        NhanVienBLL.DoDuLieuCaLamViec(rsCLV, tblCaLamViec);


    }//GEN-LAST:event_btnXoaCaLamViecActionPerformed

    private void txtTenCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenCaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenCaActionPerformed

    private void txtGioKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGioKetThucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGioKetThucActionPerformed

    private void txtGioBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGioBatDauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGioBatDauActionPerformed

    private void btnSuaCaLamViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaCaLamViecActionPerformed
        // TODO add your handling code here:
        String tenca = txtTenCa.getText().trim();
        String maca = txtMaCa.getText().trim();
        String giobatdau = txtGioBatDau.getText().trim();
        String gioketthuc = txtGioKetThuc.getText().trim();
        String ghichu = txtGhiChu.getText().trim();
        int idcalamviec = Integer.parseInt(txtIDCaLamViec.getText());
        CaLamViecDTO clv = new CaLamViecDTO(idcalamviec, maca, tenca, giobatdau, gioketthuc, ghichu);
        
       NhanVienBLL.SuaCaLamViec(clv);
         ResultSet rs = NhanVienBLL.LayTatCaDuLieuCaLamViec();
        NhanVienBLL.DoDuLieuCaLamViec(rs, tblCaLamViec);
    }//GEN-LAST:event_btnSuaCaLamViecActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ResultSet rs = NhanVienBLL.LayTatCaDuLieuCaLamViec();
        //Thực hiện đổ dữ liệu vào table
        NhanVienBLL.DoDuLieuCaLamViec(rs, tblCaLamViec);
    }//GEN-LAST:event_formWindowOpened

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        int index = tblCaLamViec.getSelectedRow();
        txtIDCaLamViec.setText(tblCaLamViec.getValueAt(index, 1).toString());
        txtMaCa.setText(tblCaLamViec.getValueAt(index, 2).toString());
        txtTenCa.setText(tblCaLamViec.getValueAt(index, 3).toString());
        txtGioBatDau.setText(tblCaLamViec.getValueAt(index, 4).toString());
        txtGioKetThuc.setText(tblCaLamViec.getValueAt(index, 5).toString());
        txtGhiChu.setText(tblCaLamViec.getValueAt(index, 6).toString());
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCaLamViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCaLamViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCaLamViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCaLamViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCaLamViec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaCaLamViec;
    private javax.swing.JButton btnThemCaLamViec;
    private javax.swing.JButton btnXoaCaLamViec;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGioBatDau;
    private javax.swing.JLabel lblGioKetThuc;
    private javax.swing.JLabel lblIDcalamviec;
    private javax.swing.JLabel lblMaCa;
    private javax.swing.JLabel lblMoTa;
    private javax.swing.JLabel lblTenCa;
    private javax.swing.JTable tblCaLamViec;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtGioBatDau;
    private javax.swing.JTextField txtGioKetThuc;
    private javax.swing.JTextField txtIDCaLamViec;
    private javax.swing.JTextField txtMaCa;
    private javax.swing.JTextField txtTenCa;
    // End of variables declaration//GEN-END:variables
}
