package Presentation;

import BLL.ComboBoxBLL;
import BLL.NhanVienBLL;
import BLL.QuyenNhanVienBLL;
import static BLL.ThongBao_ChuyenDoi.*;
import static DAL.NhanVienDAL.iQuyenND;
import DTO.NhanVien;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Administrator
 */
public class frmNhanVien extends javax.swing.JFrame {

    String macDinh = "image\\Nhan_vien\\Default_Picture.png";
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    Date currentDate = new Date();
    SimpleDateFormat sdf2 = new SimpleDateFormat("ddMMyyhhmmss");

    int width = 172;    //width of the image
    int height = 140;   //height of the image
    File f = null;
    BufferedImage image = null;

    /**
     * Creates new form frmNhanVien
     */
    public frmNhanVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrGioiTinh = new javax.swing.ButtonGroup();
        pnlNhanVien = new javax.swing.JPanel();
        pnlThongTin = new javax.swing.JPanel();
        txtMaNhanVien = new javax.swing.JTextField();
        lblMaNV = new javax.swing.JLabel();
        radNam = new javax.swing.JRadioButton();
        radNu = new javax.swing.JRadioButton();
        lblGioiTinh = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lblDiaChi = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblNgayVaoLam = new javax.swing.JLabel();
        lblGhiChu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaGhiChu = new javax.swing.JTextArea();
        txtTenNhanVien = new javax.swing.JTextField();
        lblTenNV = new javax.swing.JLabel();
        btnChonAnh = new javax.swing.JButton();
        dateNgaySinh = new com.toedter.calendar.JDateChooser();
        dateNgayVaolam = new com.toedter.calendar.JDateChooser();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        dtpAnhNV = new javax.swing.JDesktopPane();
        lblPicture = new javax.swing.JLabel();
        btnTaoMoi = new javax.swing.JButton();
        lblchucvu = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        pnlDanhSachNV = new javax.swing.JPanel();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHome = new javax.swing.JMenu();
        mnuiTrangChu = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuiExit = new javax.swing.JMenuItem();
        mnuQuanly = new javax.swing.JMenu();
        mnuSanPham = new javax.swing.JMenu();
        mnuiLoaiSanPham = new javax.swing.JMenuItem();
        mnuiNhaCungCap = new javax.swing.JMenuItem();
        mnuiSanPham = new javax.swing.JMenuItem();
        mnuHoaDon = new javax.swing.JMenu();
        mnuiQLHDNhap = new javax.swing.JMenuItem();
        mnuiQLHDXuat = new javax.swing.JMenuItem();
        mnuiCTHD = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuKhachHang = new javax.swing.JMenuItem();
        mnuNhanVien = new javax.swing.JMenuItem();
        mnuQLTaiKhoan = new javax.swing.JMenuItem();
        mnuHoadon = new javax.swing.JMenu();
        mnuTaoHoaDon = new javax.swing.JMenu();
        mnuiHDNhap = new javax.swing.JMenuItem();
        mnuiHDXuat = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mnuTKHoaDon = new javax.swing.JMenuItem();
        mnuTKNhanVien = new javax.swing.JMenuItem();
        mnuTaiKhoan = new javax.swing.JMenu();
        mnuiDangKy = new javax.swing.JMenuItem();
        mnuiDoiMK = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenu();
        mnuiBanQuyen = new javax.swing.JMenuItem();
        mnuDangXuat = new javax.swing.JMenu();
        mnuTime = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BH - Quản lý nhân viên");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlNhanVien.setBackground(new java.awt.Color(170, 234, 240));
        pnlNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 1, true), "Quản lý nhân viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20), new java.awt.Color(255, 0, 0))); // NOI18N

        pnlThongTin.setBackground(new java.awt.Color(170, 234, 240));
        pnlThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 1, true), "Thông tin nhân viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14), new java.awt.Color(51, 102, 255))); // NOI18N
        pnlThongTin.setToolTipText("");

        txtMaNhanVien.setEditable(false);
        txtMaNhanVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblMaNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaNV.setText("Mã Nhân Viên :");

        radNam.setBackground(new java.awt.Color(170, 234, 240));
        btngrGioiTinh.add(radNam);
        radNam.setSelected(true);
        radNam.setText("Nam");

        radNu.setBackground(new java.awt.Color(170, 234, 240));
        btngrGioiTinh.add(radNu);
        radNu.setText("Nữ");

        lblGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblGioiTinh.setText("Giới Tính : ");

        lblNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNgaySinh.setText("Ngày Sinh :");

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblDiaChi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDiaChi.setText("Địa Chỉ :");

        lblSoDienThoai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSoDienThoai.setText("Số Điện Thoại :");

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblNgayVaoLam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNgayVaoLam.setText("Ngày Vào Làm :");

        lblGhiChu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblGhiChu.setText("Ghi Chú ");

        txtaGhiChu.setColumns(20);
        txtaGhiChu.setLineWrap(true);
        txtaGhiChu.setRows(5);
        txtaGhiChu.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtaGhiChu);

        txtTenNhanVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblTenNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTenNV.setText("Tên nhân viên :");

        btnChonAnh.setBackground(new java.awt.Color(255, 255, 255));
        btnChonAnh.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnChonAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/choosepic.png"))); // NOI18N
        btnChonAnh.setText("Chọn ảnh");
        btnChonAnh.setToolTipText("Ảnh 172x140 pixel sẽ có chất lượng tốt nhất.");
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });

        dateNgaySinh.setDateFormatString("dd/MM/yyyy");
        dateNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        dateNgayVaolam.setDateFormatString("dd/MM/yyyy");
        dateNgayVaolam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnSua.setBackground(new java.awt.Color(255, 255, 255));
        btnSua.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setToolTipText("Chọn 1 bản ghi bất kì để sửa sau đó click sửa để lưu");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/xoa.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setToolTipText("Chọn bản ghi sau đó click để xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setToolTipText("Nhập đầy đủ thông tin sau đó click để thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        dtpAnhNV.setBackground(new java.awt.Color(255, 255, 255));

        lblPicture.setToolTipText("172x140 pixel");

        dtpAnhNV.setLayer(lblPicture, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dtpAnhNVLayout = new javax.swing.GroupLayout(dtpAnhNV);
        dtpAnhNV.setLayout(dtpAnhNVLayout);
        dtpAnhNVLayout.setHorizontalGroup(
            dtpAnhNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dtpAnhNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );
        dtpAnhNVLayout.setVerticalGroup(
            dtpAnhNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dtpAnhNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnTaoMoi.setBackground(new java.awt.Color(255, 255, 255));
        btnTaoMoi.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnTaoMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        btnTaoMoi.setText("Tạo mới");
        btnTaoMoi.setToolTipText("Về trạng thái ban đầu");
        btnTaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoiActionPerformed(evt);
            }
        });

        lblchucvu.setText("Chức vụ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlThongTinLayout = new javax.swing.GroupLayout(pnlThongTin);
        pnlThongTin.setLayout(pnlThongTinLayout);
        pnlThongTinLayout.setHorizontalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDiaChi)
                                    .addComponent(lblSoDienThoai)
                                    .addComponent(lblNgayVaoLam))
                                .addGap(30, 30, 30)
                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSDT)
                                    .addComponent(txtDiaChi)))
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGioiTinh)
                                    .addComponent(lblNgaySinh))
                                .addGap(54, 54, 54)
                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                                        .addComponent(radNam)
                                        .addGap(32, 32, 32)
                                        .addComponent(radNu))
                                    .addComponent(dateNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTenNV)
                                    .addComponent(lblMaNV))
                                .addGap(29, 29, 29)
                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenNhanVien)
                                    .addComponent(txtMaNhanVien))))
                        .addGap(15, 15, 15)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtpAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinLayout.createSequentialGroup()
                                .addComponent(btnChonAnh)
                                .addGap(33, 33, 33))))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTaoMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinLayout.createSequentialGroup()
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGhiChu)
                                    .addComponent(lblchucvu))
                                .addGap(70, 70, 70)
                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(dateNgayVaolam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(207, 207, 207)))
                .addContainerGap())
        );
        pnlThongTinLayout.setVerticalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaNV)
                            .addComponent(txtMaNhanVien))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenNV)
                            .addComponent(txtTenNhanVien))
                        .addGap(11, 11, 11)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGioiTinh)
                            .addComponent(radNam)
                            .addComponent(radNu))
                        .addGap(11, 11, 11)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNgaySinh)
                            .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiaChi)
                            .addComponent(txtDiaChi))
                        .addGap(11, 11, 11)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSoDienThoai)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNgayVaoLam)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addComponent(dateNgayVaolam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblchucvu)))))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addComponent(dtpAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChonAnh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addComponent(lblGhiChu)
                        .addGap(123, 123, 123))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa)
                    .addComponent(btnThem))
                .addContainerGap())
        );

        pnlDanhSachNV.setBackground(new java.awt.Color(170, 234, 240));
        pnlDanhSachNV.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 1, true), "Danh sách nhân viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14), new java.awt.Color(51, 102, 255))); // NOI18N

        lblTimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTimKiem.setText("Tìm kiếm nhân viên");

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTimKiem.setToolTipText("Nhập tên, địa chỉ hoặc mô tả để tìm kiếm");
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(500, 500));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(900, 500));

        tblNhanVien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã nhân viên", "Tên nhân viên", "Giới tính", "Ngày sinh", "Địa chỉ", "SĐT", "Ngày vào làm", "Ghi chú", "Quyền", "Picture"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.setMaximumSize(new java.awt.Dimension(2147483647, 400));
        tblNhanVien.setMinimumSize(new java.awt.Dimension(500, 160));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        jScrollPane3.setViewportView(jScrollPane1);

        javax.swing.GroupLayout pnlDanhSachNVLayout = new javax.swing.GroupLayout(pnlDanhSachNV);
        pnlDanhSachNV.setLayout(pnlDanhSachNVLayout);
        pnlDanhSachNVLayout.setHorizontalGroup(
            pnlDanhSachNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhSachNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDanhSachNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                    .addGroup(pnlDanhSachNVLayout.createSequentialGroup()
                        .addComponent(lblTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDanhSachNVLayout.setVerticalGroup(
            pnlDanhSachNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDanhSachNVLayout.createSequentialGroup()
                .addGroup(pnlDanhSachNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimKiem)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDanhSachNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDanhSachNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mnuHome.setText("Home");

        mnuiTrangChu.setText("Trang chủ");
        mnuiTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiTrangChuActionPerformed(evt);
            }
        });
        mnuHome.add(mnuiTrangChu);
        mnuHome.add(jSeparator4);

        mnuiExit.setText("Thoát");
        mnuiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiExitActionPerformed(evt);
            }
        });
        mnuHome.add(mnuiExit);

        jMenuBar1.add(mnuHome);

        mnuQuanly.setText("Quản lý");

        mnuSanPham.setText("Sản phẩm");

        mnuiLoaiSanPham.setText("Loại sản phẩm");
        mnuiLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiLoaiSanPhamActionPerformed(evt);
            }
        });
        mnuSanPham.add(mnuiLoaiSanPham);

        mnuiNhaCungCap.setText("Nhà cung cấp");
        mnuiNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiNhaCungCapActionPerformed(evt);
            }
        });
        mnuSanPham.add(mnuiNhaCungCap);

        mnuiSanPham.setText("Các sản phẩm");
        mnuiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiSanPhamActionPerformed(evt);
            }
        });
        mnuSanPham.add(mnuiSanPham);

        mnuQuanly.add(mnuSanPham);

        mnuHoaDon.setText("Hóa đơn");

        mnuiQLHDNhap.setText("Hóa đơn nhập");
        mnuHoaDon.add(mnuiQLHDNhap);

        mnuiQLHDXuat.setText("Hóa đơn xuất");
        mnuiQLHDXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiQLHDXuatActionPerformed(evt);
            }
        });
        mnuHoaDon.add(mnuiQLHDXuat);

        mnuiCTHD.setText("Chi tiết hóa đơn");
        mnuiCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiCTHDActionPerformed(evt);
            }
        });
        mnuHoaDon.add(mnuiCTHD);

        mnuQuanly.add(mnuHoaDon);
        mnuQuanly.add(jSeparator2);

        mnuKhachHang.setText("Khách hàng");
        mnuKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKhachHangActionPerformed(evt);
            }
        });
        mnuQuanly.add(mnuKhachHang);

        mnuNhanVien.setText("Nhân viên");
        mnuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNhanVienActionPerformed(evt);
            }
        });
        mnuQuanly.add(mnuNhanVien);

        mnuQLTaiKhoan.setText("Tài khoản người dùng");
        mnuQLTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQLTaiKhoanActionPerformed(evt);
            }
        });
        mnuQuanly.add(mnuQLTaiKhoan);

        jMenuBar1.add(mnuQuanly);

        mnuHoadon.setText("Hóa đơn");

        mnuTaoHoaDon.setText("Tạo hóa đơn");

        mnuiHDNhap.setText("Hóa đơn nhập");
        mnuiHDNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiHDNhapActionPerformed(evt);
            }
        });
        mnuTaoHoaDon.add(mnuiHDNhap);

        mnuiHDXuat.setText("Hóa đơn xuất");
        mnuiHDXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiHDXuatActionPerformed(evt);
            }
        });
        mnuTaoHoaDon.add(mnuiHDXuat);

        mnuHoadon.add(mnuTaoHoaDon);

        jMenuBar1.add(mnuHoadon);

        mnuThongKe.setText("Thống kê");

        mnuTKHoaDon.setText("Hóa đơn");
        mnuTKHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTKHoaDonActionPerformed(evt);
            }
        });
        mnuThongKe.add(mnuTKHoaDon);

        mnuTKNhanVien.setText("Nhân viên");
        mnuThongKe.add(mnuTKNhanVien);

        jMenuBar1.add(mnuThongKe);

        mnuTaiKhoan.setText("Tài khoản");

        mnuiDangKy.setText("Đăng ký");
        mnuiDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiDangKyActionPerformed(evt);
            }
        });
        mnuTaiKhoan.add(mnuiDangKy);

        mnuiDoiMK.setText("Đổi mật khẩu");
        mnuiDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiDoiMKActionPerformed(evt);
            }
        });
        mnuTaiKhoan.add(mnuiDoiMK);

        jMenuBar1.add(mnuTaiKhoan);

        mnuAbout.setText("Thông tin");

        mnuiBanQuyen.setText("Bản quyền");
        mnuiBanQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiBanQuyenActionPerformed(evt);
            }
        });
        mnuAbout.add(mnuiBanQuyen);

        jMenuBar1.add(mnuAbout);

        mnuDangXuat.setText("Đăng xuất");
        mnuDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuDangXuatMousePressed(evt);
            }
        });
        jMenuBar1.add(mnuDangXuat);

        mnuTime.setBackground(new java.awt.Color(255, 0, 0));
        jMenuBar1.add(mnuTime);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        //Lấy dữ liệu từ form gán vào các biến
//        String tenNV = txtTenNhanVien.getText().trim();
//        String diaChi = txtDiaChi.getText().trim();
//        String sdt = txtSDT.getText().trim();
//        String ngaySinh = DoiDateChooser(dateNgaySinh).getText();
//        String ngayVaoLam = DoiDateChooser(dateNgayVaolam).getText();
//        String ghiChu = txtaGhiChu.getText().trim();
//
//        //Gọi hàm lấy ID của phần tử trong cbb
//        int quyen = Integer.parseInt(ComboBoxBLL.getSelectedItemID(cbbQuyenNV));
//
//        //Gọi hàm đổi giới tính sang int
//        int gioiTinh = GioiTinhBoolean(radNam);
//        Date randomDate = new Date();
//        //write image
//        f = new File("image\\Nhan_vien\\anh_" + sdf2.format(randomDate) + ".png");
//
//        ghiFileAnh(image, f);
//
//        String hinhAnh = f.getName();
//
//        //Tạo đối tượng NhanVien từ DTO
//        NhanVien nv = new NhanVien(0, tenNV, diaChi, sdt, gioiTinh, ngaySinh, ngayVaoLam, "", "", quyen, ghiChu, hinhAnh);
//
//        //Gọi hàm ThemNhanVien từ BLL để tiến hành thêm vào CSDL
//        NhanVienBLL.ThemNhanVien(nv);
//
//        //Tạo biến ResultSet và thực hiện gán dữ liệu được lấy từ BLL qua hàm LayThongTinNhanVien()
//        ResultSet rs = NhanVienBLL.LayThongTinNhanVien();
//        //Gọi hàm đổ dữ liệu vào table THẬT từ BLL
//        NhanVienBLL.DoDuLieuNhanVien(rs, tblNhanVien);
    }//GEN-LAST:event_btnThemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        DongHo(mnuTime);
    // Tạo biến ResultSet và thực hiện đổ dữ liệu
            ResultSet rs=NhanVienBLL.LayNhanVien();
            //Thực hiện đổ dữ liệu vào table
            NhanVienBLL.DoDuLieu(rs, tblNhanVien);
//PhanQuyen(mnuNhanVien, mnuQLTaiKhoan, mnuiDangKy, iQuyenND);
//        //Tạo biến ResultSet và thực hiện gán dữ liệu được lấy từ BLL qua hàm LayThongTinNhanVien()
//        ResultSet rsNV = NhanVienBLL.LayThongTinNhanVien();
//        //Gọi hàm đổ dữ liệu vào table THẬT từ BLL
//        NhanVienBLL.DoDuLieuNhanVien(rsNV, tblNhanVien);
//
//        //Tạo biến rs để chứa dữ liệu từ của QuyenNhanVienBLL
//        ResultSet rsQuyen = QuyenNhanVienBLL.LayThongTinQuyen();
//        //Gọi hàm để đổ dữ liệu vào Combobox
//        ComboBoxBLL.LoadDuLieuCombobox(rsQuyen, cbbQuyenNV, "TenQuyen", "MaQuyen");
//
//        //Gọi hàm đổi sang ô text
//        DoiDateChooser(dateNgayVaolam).setText(sdf.format(currentDate));
//
//        f = new File(macDinh);
//        image = DocFileAnh(f);
//        lblPicture.setIcon(new ImageIcon(image.getScaledInstance(width, height, BufferedImage.TYPE_INT_ARGB)));
    }//GEN-LAST:event_formWindowOpened

    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhActionPerformed
        JFileChooser choose = new JFileChooser();
        choose.setDialogTitle("Chọn 1 tấm ảnh");
        choose.setMultiSelectionEnabled(false);

        int result = choose.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {

            //read image file
            f = choose.getSelectedFile();
            f = new File(f.getAbsolutePath());

            image = DocFileAnh(f);
            lblPicture.setIcon(new ImageIcon(image.getScaledInstance(width, height, BufferedImage.TYPE_INT_ARGB)));
        }
    }//GEN-LAST:event_btnChonAnhActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        /*
        Tạo biến index là vị trí dòng được chọn kiểu Integer
        Mục đích: lưu vị trí dòng đầu tiên được chọn trong table
         */

        int index = tblNhanVien.getSelectedRow();

        //Gán các textfield trong form là các giá trị của dòng được chọn với vị trí index
        txtMaNhanVien.setText(tblNhanVien.getValueAt(index, 1).toString());
        txtTenNhanVien.setText(tblNhanVien.getValueAt(index, 2).toString());

        txtaGhiChu.setText(tblNhanVien.getValueAt(index, 8).toString());
        txtDiaChi.setText(tblNhanVien.getValueAt(index, 5).toString());
        txtSDT.setText(tblNhanVien.getValueAt(index, 6).toString());
        //Gọi hàm đổi sang ô text
        DoiDateChooser(dateNgayVaolam).setText(tblNhanVien.getValueAt(index, 7).toString());
        DoiDateChooser(dateNgaySinh).setText(tblNhanVien.getValueAt(index, 4).toString());
        //Gọi hàm chọn radio button phù hợp
        String gioiTinh = tblNhanVien.getValueAt(index, 3).toString();
        chonRadio(gioiTinh, radNam, radNu);

        //Tạo biến và gọi hàm chuyển đổi combobox
        String quyen = tblNhanVien.getValueAt(index, 9).toString();
        ComboBoxBLL.setSelectedCombobox(cbbQuyenNV, quyen);

        String maNV = tblNhanVien.getValueAt(index, 1).toString();
        String fileAnh = NhanVienBLL.LayAnh(maNV);
        
        /*
        Thực hiện đọc ảnh của từng nhân viên
        */
        File anh = new File("image\\Nhan_vien\\" + fileAnh);
        try {
            image = DocFileAnh(anh);
            lblPicture.setIcon(new ImageIcon(image.getScaledInstance(width, height, BufferedImage.TYPE_INT_ARGB)));
        } catch (NullPointerException e) {
            anh = new File(macDinh);
            image = DocFileAnh(anh);
            lblPicture.setIcon(new ImageIcon(image.getScaledInstance(width, height, BufferedImage.TYPE_INT_ARGB)));
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        //Thực hiện bắt lỗi
//        try {
//            //Lấy dữ liệu từ form gán vào các biến
//            int maNV = Integer.parseInt(txtMaNhanVien.getText().trim());
//            String tenNV = txtTenNhanVien.getText().trim();
//            String diaChi = txtDiaChi.getText().trim();
//            String sdt = txtSDT.getText().trim();
//            String ngaySinh = DoiDateChooser(dateNgaySinh).getText();
//            String ngayVaoLam = DoiDateChooser(dateNgayVaolam).getText();
//            String ghiChu = txtaGhiChu.getText().trim();
//
//            //Gọi hàm lấy ID của phần tử trong cbb
//            int quyen = Integer.parseInt(ComboBoxBLL.getSelectedItemID(cbbQuyenNV));
//
//            //Gọi hàm đổi giới tính sang int
//            int gioiTinh = GioiTinhBoolean(radNam);
//            Date randomDate = new Date();
//            //write image
//            f = new File("image\\Nhan_vien\\anh_" + sdf2.format(randomDate) + ".png");
//            ghiFileAnh(image, f);
//
//            String hinhAnh = f.getName();
//            System.out.println(sdf2.format(randomDate));
//
//            //Tạo đối tượng NhanVien từ DTO
//            NhanVien nv = new NhanVien(maNV, tenNV, diaChi, sdt, gioiTinh, ngaySinh, ngayVaoLam, "", "", quyen, ghiChu, hinhAnh);
//            //Gọi hàm SuaNhanVien từ BLL để tiến hành sửa dữ liệu trong DB
//            NhanVienBLL.SuaNhanVien(nv);
//
//            //Tạo biến ResultSet và thực hiện gán dữ liệu được sau khi sửa
//            ResultSet rsNV = NhanVienBLL.LayThongTinNhanVien();
//            //Gọi hàm đổ dữ liệu vào table THẬT từ BLL
//            NhanVienBLL.DoDuLieuNhanVien(rsNV, tblNhanVien);
//
//        } catch (NumberFormatException e) {
//            ThongBao("Vui lòng chọn bản ghi cần sửa !", "Thông báo", 1);
//        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        NhanVienBLL.XoaNhanVien(tblNhanVien);

        //Tạo biến ResultSet và thực hiện gán dữ liệu được sau khi xóa
        ResultSet rsNV = NhanVienBLL.LayThongTinNhanVien();
        //Gọi hàm đổ dữ liệu vào table THẬT từ BLL
        NhanVienBLL.DoDuLieuNhanVien(rsNV, tblNhanVien);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMoiActionPerformed
        //Thực hiện gán dữ liệu cho các textfield, radio, combobox trên form
//        txtDiaChi.setText("");
//        txtTenNhanVien.setText("");
//        cbbQuyenNV.setSelectedIndex(0);
//        radNam.setSelected(true);
//        txtMaNhanVien.setText("");
//        txtSDT.setText("");
//        txtTimKiem.setText("");
//        txtaGhiChu.setText("");
//        //Gọi hàm đổi sang ô text
//        DoiDateChooser(dateNgaySinh).setText("");
//        DoiDateChooser(dateNgayVaolam).setText(sdf.format(currentDate));
//
//        //Gọi hàm để lấy dữ liệu lúc chưa tìm kiếm
//        ResultSet rsTimKiem = NhanVienBLL.TimKiemNhanVien("");
//        NhanVienBLL.DoDuLieuNhanVien(rsTimKiem, tblNhanVien);
//        f = new File(macDinh);
//        image = DocFileAnh(f);
//        lblPicture.setIcon(new ImageIcon(image.getScaledInstance(width, height, BufferedImage.TYPE_INT_ARGB)));
    }//GEN-LAST:event_btnTaoMoiActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        //Biến chứa từ khóa cần tìm 
//        String tuKhoa = txtTimKiem.getText().trim();
//
//        //Gọi hàm và đổ dữ liệu vừa tìm kiếm vào bảng
//        ResultSet rsTimKiem = NhanVienBLL.TimKiemNhanVien(tuKhoa);
//        NhanVienBLL.DoDuLieuNhanVien(rsTimKiem, tblNhanVien);
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void mnuiTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiTrangChuActionPerformed
//        frmTrangChinh tc = new frmTrangChinh();
//        tc.show();
//        this.dispose();
    }//GEN-LAST:event_mnuiTrangChuActionPerformed

    private void mnuiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiExitActionPerformed
//        CauHoiThoat();
    }//GEN-LAST:event_mnuiExitActionPerformed

    private void mnuiLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiLoaiSanPhamActionPerformed
//        frmLoaiSanPham lsp = new frmLoaiSanPham();
//        lsp.show();
//        this.dispose();
    }//GEN-LAST:event_mnuiLoaiSanPhamActionPerformed

    private void mnuiNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiNhaCungCapActionPerformed
//        frmNhaCungCap ncc = new frmNhaCungCap();
//        ncc.show();
//        this.dispose();
    }//GEN-LAST:event_mnuiNhaCungCapActionPerformed

    private void mnuiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiSanPhamActionPerformed
//        frmSanPham sp = new frmSanPham();
//        sp.show();
//        this.dispose();
    }//GEN-LAST:event_mnuiSanPhamActionPerformed

    private void mnuiQLHDXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiQLHDXuatActionPerformed
//        frmHoaDon hd = new frmHoaDon();
//        hd.show();
//        this.dispose();
    }//GEN-LAST:event_mnuiQLHDXuatActionPerformed

    private void mnuiCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiCTHDActionPerformed
//        frmChiTietHoaDon cthd = new frmChiTietHoaDon();
//        cthd.show();
//        this.dispose();
    }//GEN-LAST:event_mnuiCTHDActionPerformed

    private void mnuKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKhachHangActionPerformed
//        frmKhachHang kh = new frmKhachHang();
//        kh.show();
//        this.dispose();
    }//GEN-LAST:event_mnuKhachHangActionPerformed

    private void mnuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNhanVienActionPerformed
//        frmNhanVien nv = new frmNhanVien();
//        nv.show();
//        this.dispose();
    }//GEN-LAST:event_mnuNhanVienActionPerformed

    private void mnuQLTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQLTaiKhoanActionPerformed
//        frmDiemDanh qlnd = new frmDiemDanh();
//        qlnd.show();
//        this.dispose();
    }//GEN-LAST:event_mnuQLTaiKhoanActionPerformed

    private void mnuiHDNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiHDNhapActionPerformed
//        frmPhieuNhap pn = new frmPhieuNhap();
//        pn.show();
//        this.dispose();
    }//GEN-LAST:event_mnuiHDNhapActionPerformed

    private void mnuiHDXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiHDXuatActionPerformed
//        frmTaoHoaDon thd = new frmTaoHoaDon();
//        thd.show();
//        this.dispose();
    }//GEN-LAST:event_mnuiHDXuatActionPerformed

    private void mnuTKHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTKHoaDonActionPerformed
//        frmBangThongKe btk = new frmBangThongKe();
//        btk.show();
//        this.dispose();
    }//GEN-LAST:event_mnuTKHoaDonActionPerformed

    private void mnuiDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiDangKyActionPerformed
//        frmDangKy dk = new frmDangKy();
//        dk.show();
    }//GEN-LAST:event_mnuiDangKyActionPerformed

    private void mnuiDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiDoiMKActionPerformed
//        frmDoiMatKhau dmk = new frmDoiMatKhau();
//        dmk.show();
    }//GEN-LAST:event_mnuiDoiMKActionPerformed

    private void mnuiBanQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiBanQuyenActionPerformed
//        frmBanQuyen bq = new frmBanQuyen();
//        bq.show();
    }//GEN-LAST:event_mnuiBanQuyenActionPerformed

    private void mnuDangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuDangXuatMousePressed
        frmDangNhap dn = new frmDangNhap();
        dn.show();
        this.dispose();
    }//GEN-LAST:event_mnuDangXuatMousePressed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTaoMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup btngrGioiTinh;
    private com.toedter.calendar.JDateChooser dateNgaySinh;
    private com.toedter.calendar.JDateChooser dateNgayVaolam;
    private javax.swing.JDesktopPane dtpAnhNV;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNgayVaoLam;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblchucvu;
    private javax.swing.JMenu mnuAbout;
    private javax.swing.JMenu mnuDangXuat;
    private javax.swing.JMenu mnuHoaDon;
    private javax.swing.JMenu mnuHoadon;
    private javax.swing.JMenu mnuHome;
    private javax.swing.JMenuItem mnuKhachHang;
    private javax.swing.JMenuItem mnuNhanVien;
    private javax.swing.JMenuItem mnuQLTaiKhoan;
    private javax.swing.JMenu mnuQuanly;
    private javax.swing.JMenu mnuSanPham;
    private javax.swing.JMenuItem mnuTKHoaDon;
    private javax.swing.JMenuItem mnuTKNhanVien;
    private javax.swing.JMenu mnuTaiKhoan;
    private javax.swing.JMenu mnuTaoHoaDon;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuTime;
    private javax.swing.JMenuItem mnuiBanQuyen;
    private javax.swing.JMenuItem mnuiCTHD;
    private javax.swing.JMenuItem mnuiDangKy;
    private javax.swing.JMenuItem mnuiDoiMK;
    private javax.swing.JMenuItem mnuiExit;
    private javax.swing.JMenuItem mnuiHDNhap;
    private javax.swing.JMenuItem mnuiHDXuat;
    private javax.swing.JMenuItem mnuiLoaiSanPham;
    private javax.swing.JMenuItem mnuiNhaCungCap;
    private javax.swing.JMenuItem mnuiQLHDNhap;
    private javax.swing.JMenuItem mnuiQLHDXuat;
    private javax.swing.JMenuItem mnuiSanPham;
    private javax.swing.JMenuItem mnuiTrangChu;
    private javax.swing.JPanel pnlDanhSachNV;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JPanel pnlThongTin;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextArea txtaGhiChu;
    // End of variables declaration//GEN-END:variables
}
