package com.javaweb.model;
// Generated Feb 23, 2017 11:29:16 AM by Hibernate Tools 4.3.1



/**
 * Calamviec generated by hbm2java
 */
public class Calamviec  implements java.io.Serializable {


     private Integer idcalamviec;
     private String maca;
     private String tenca;
     private String giobatdau;
     private String gioketthuc;
     private String ghichu;

    public Calamviec() {
    }

	
    public Calamviec(String maca, String tenca, String giobatdau, String gioketthuc) {
        this.maca = maca;
        this.tenca = tenca;
        this.giobatdau = giobatdau;
        this.gioketthuc = gioketthuc;
    }
    public Calamviec(String maca, String tenca, String giobatdau, String gioketthuc, String ghichu) {
       this.maca = maca;
       this.tenca = tenca;
       this.giobatdau = giobatdau;
       this.gioketthuc = gioketthuc;
       this.ghichu = ghichu;
    }
   
    public Integer getIdcalamviec() {
        return this.idcalamviec;
    }
    
    public void setIdcalamviec(Integer idcalamviec) {
        this.idcalamviec = idcalamviec;
    }
    public String getMaca() {
        return this.maca;
    }
    
    public void setMaca(String maca) {
        this.maca = maca;
    }
    public String getTenca() {
        return this.tenca;
    }
    
    public void setTenca(String tenca) {
        this.tenca = tenca;
    }
    public String getGiobatdau() {
        return this.giobatdau;
    }
    
    public void setGiobatdau(String giobatdau) {
        this.giobatdau = giobatdau;
    }
    public String getGioketthuc() {
        return this.gioketthuc;
    }
    
    public void setGioketthuc(String gioketthuc) {
        this.gioketthuc = gioketthuc;
    }
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }




}


