package com.javaweb.model;
// Generated Feb 23, 2017 11:29:16 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Diemdanh generated by hbm2java
 */
public class Diemdanh  implements java.io.Serializable {


     private Integer idbaodanh;
     private int nhanvien;
     private int calamviec;
     private Date thoigian;
     private String ghichu;

    public Diemdanh() {
    }

	
    public Diemdanh(int nhanvien, int calamviec, Date thoigian) {
        this.nhanvien = nhanvien;
        this.calamviec = calamviec;
        this.thoigian = thoigian;
    }
    public Diemdanh(int nhanvien, int calamviec, Date thoigian, String ghichu) {
       this.nhanvien = nhanvien;
       this.calamviec = calamviec;
       this.thoigian = thoigian;
       this.ghichu = ghichu;
    }
   
    public Integer getIdbaodanh() {
        return this.idbaodanh;
    }
    
    public void setIdbaodanh(Integer idbaodanh) {
        this.idbaodanh = idbaodanh;
    }
    public int getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(int nhanvien) {
        this.nhanvien = nhanvien;
    }
    public int getCalamviec() {
        return this.calamviec;
    }
    
    public void setCalamviec(int calamviec) {
        this.calamviec = calamviec;
    }
    public Date getThoigian() {
        return this.thoigian;
    }
    
    public void setThoigian(Date thoigian) {
        this.thoigian = thoigian;
    }
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }




}


