package com.javaweb.model;
// Generated Feb 13, 2017 8:24:56 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Giolam generated by hbm2java
 */
public class Giolam  implements java.io.Serializable {


     private Integer idgiolam;
     private int nhanvien;
     private int calamviec;
     private Date giovao;
     private Date giora;
     private Boolean lamho;
     private String ghichu;

    public Giolam() {
    }

	
    public Giolam(int nhanvien, int calamviec, Date giovao, Date giora) {
        this.nhanvien = nhanvien;
        this.calamviec = calamviec;
        this.giovao = giovao;
        this.giora = giora;
    }
    public Giolam(int nhanvien, int calamviec, Date giovao, Date giora, Boolean lamho, String ghichu) {
       this.nhanvien = nhanvien;
       this.calamviec = calamviec;
       this.giovao = giovao;
       this.giora = giora;
       this.lamho = lamho;
       this.ghichu = ghichu;
    }
   
    public Integer getIdgiolam() {
        return this.idgiolam;
    }
    
    public void setIdgiolam(Integer idgiolam) {
        this.idgiolam = idgiolam;
    }
    public int getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(int nhanvien) {
        this.nhanvien = nhanvien;
    }
    public int getCalamviec() {
        return this.calamviec;
    }
    
    public void setCalamviec(int calamviec) {
        this.calamviec = calamviec;
    }
    public Date getGiovao() {
        return this.giovao;
    }
    
    public void setGiovao(Date giovao) {
        this.giovao = giovao;
    }
    public Date getGiora() {
        return this.giora;
    }
    
    public void setGiora(Date giora) {
        this.giora = giora;
    }
    public Boolean getLamho() {
        return this.lamho;
    }
    
    public void setLamho(Boolean lamho) {
        this.lamho = lamho;
    }
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }




}


