package com.javaweb.model;
// Generated Feb 28, 2017 3:47:14 PM by Hibernate Tools 4.3.1



/**
 * Luongnv generated by hbm2java
 */
public class Luongnv  implements java.io.Serializable {


     private Integer idluongnv;
     private int chucvu;
     private double luongcoban;
     private String donvi;
     private String ghichu;

    public Luongnv() {
    }

	
    public Luongnv(int chucvu, double luongcoban, String donvi) {
        this.chucvu = chucvu;
        this.luongcoban = luongcoban;
        this.donvi = donvi;
    }
    public Luongnv(int chucvu, double luongcoban, String donvi, String ghichu) {
       this.chucvu = chucvu;
       this.luongcoban = luongcoban;
       this.donvi = donvi;
       this.ghichu = ghichu;
    }
   
    public Integer getIdluongnv() {
        return this.idluongnv;
    }
    
    public void setIdluongnv(Integer idluongnv) {
        this.idluongnv = idluongnv;
    }
    public int getChucvu() {
        return this.chucvu;
    }
    
    public void setChucvu(int chucvu) {
        this.chucvu = chucvu;
    }
    public double getLuongcoban() {
        return this.luongcoban;
    }
    
    public void setLuongcoban(double luongcoban) {
        this.luongcoban = luongcoban;
    }
    public String getDonvi() {
        return this.donvi;
    }
    
    public void setDonvi(String donvi) {
        this.donvi = donvi;
    }
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }




}


