package com.javaweb.model;
// Generated Feb 23, 2017 11:29:16 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien  implements java.io.Serializable {


     private Integer idnhanvien;
     private String hoten;
     private Date ngaysinh;
     private String sdt;
     private String diachi;
     private int chucvu;
     private boolean gioitinh;
     private Date ngayvaolam;
     private String cmnd;
     private Date ngaycap;
     private String tendn;
     private String matkhau;
     private String email;
     private String luongnv;
     private String ghichu;
     private String hinhanh;
     private String noicap;

    public Nhanvien() {
    }

	
    public Nhanvien(String hoten, Date ngaysinh, String sdt, String diachi, int chucvu, boolean gioitinh, Date ngayvaolam, String tendn, String matkhau, String luongnv) {
        this.hoten = hoten;
        this.ngaysinh = ngaysinh;
        this.sdt = sdt;
        this.diachi = diachi;
        this.chucvu = chucvu;
        this.gioitinh = gioitinh;
        this.ngayvaolam = ngayvaolam;
        this.tendn = tendn;
        this.matkhau = matkhau;
        this.luongnv = luongnv;
    }
    public Nhanvien(String hoten, Date ngaysinh, String sdt, String diachi, int chucvu, boolean gioitinh, Date ngayvaolam, String cmnd, Date ngaycap, String tendn, String matkhau, String email, String luongnv, String ghichu, String hinhanh, String noicap) {
       this.hoten = hoten;
       this.ngaysinh = ngaysinh;
       this.sdt = sdt;
       this.diachi = diachi;
       this.chucvu = chucvu;
       this.gioitinh = gioitinh;
       this.ngayvaolam = ngayvaolam;
       this.cmnd = cmnd;
       this.ngaycap = ngaycap;
       this.tendn = tendn;
       this.matkhau = matkhau;
       this.email = email;
       this.luongnv = luongnv;
       this.ghichu = ghichu;
       this.hinhanh = hinhanh;
       this.noicap = noicap;
    }
   
    public Integer getIdnhanvien() {
        return this.idnhanvien;
    }
    
    public void setIdnhanvien(Integer idnhanvien) {
        this.idnhanvien = idnhanvien;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public Date getNgaysinh() {
        return this.ngaysinh;
    }
    
    public void setNgaysinh(Date ngaysinh) {
        this.ngaysinh = ngaysinh;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public int getChucvu() {
        return this.chucvu;
    }
    
    public void setChucvu(int chucvu) {
        this.chucvu = chucvu;
    }
    public boolean isGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(boolean gioitinh) {
        this.gioitinh = gioitinh;
    }
    public Date getNgayvaolam() {
        return this.ngayvaolam;
    }
    
    public void setNgayvaolam(Date ngayvaolam) {
        this.ngayvaolam = ngayvaolam;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    public Date getNgaycap() {
        return this.ngaycap;
    }
    
    public void setNgaycap(Date ngaycap) {
        this.ngaycap = ngaycap;
    }
    public String getTendn() {
        return this.tendn;
    }
    
    public void setTendn(String tendn) {
        this.tendn = tendn;
    }
    public String getMatkhau() {
        return this.matkhau;
    }
    
    public void setMatkhau(String matkhau) {
        this.matkhau = matkhau;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLuongnv() {
        return this.luongnv;
    }
    
    public void setLuongnv(String luongnv) {
        this.luongnv = luongnv;
    }
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }
    public String getHinhanh() {
        return this.hinhanh;
    }
    
    public void setHinhanh(String hinhanh) {
        this.hinhanh = hinhanh;
    }
    public String getNoicap() {
        return this.noicap;
    }
    
    public void setNoicap(String noicap) {
        this.noicap = noicap;
    }




}


